apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-paytm
spec:
  replicas: 10
  # strategy:
  # type: paytm
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0
  selector:
     matchLabels:
      app: node-paytm
  template:
    metadata:
      labels:
        app: node-paytm
    spec:
      containers:
      - name: node-paytm
        image: 322488266669.dkr.ecr.us-east-1.amazonaws.com/nodejs_test_paytm:welcome
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
